name: mcp-data-gov-in
channels:
  - conda-forge
dependencies:
  - python=3.12
  - fastapi=0.111.0
  - uvicorn=0.30.1
  - httpx=0.27.0
  - pydantic=2.8.2
  - pydantic-settings=2.2.1
  - python-dotenv=1.0.1
  - pytest=8.2.1
  - pytest-asyncio=0.23.6
  - bandit=1.8.6
  - pip
  - pip:
    - mcp>=1.10.0
