name: mcp-data-gov-in
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.12
  - httpx=0.27.0
  - pytest=8.2.1
  - pytest-asyncio=0.23.6
  - numpy>=1.24.0
  - faiss-cpu>=1.8.0
  - sentence-transformers>=2.7.0
  - mcp>=1.10.0
  - uvicorn>=0.24.0
  - fastapi>=0.104.0
