name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
      - name: Run tests
        run: |
          micromamba run -n mcp-data-gov-in pytest -q
      - name: Run security checks
        run: |
          micromamba run -n mcp-data-gov-in bandit -r app -lll
